title: Prison Books Collective
general_email: prisonbooks@gmail.com
help_email: helpout@prisonbooks.info
description: A Durham-based all-volunteer group sending books and resources to imprisoned people across North Carolina and Alabama.
baseurl: 
url: "http://prisonbooks.info" # the base hostname & protocol for your site
twitter_username: BooksPrison
instagram_username: prisonbookscollective
facebook_username: prisonbookscollective

# Build settings
markdown: kramdown
